---
title: "morphology_analysis"
author: "Allison Davis"
date: "November 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data collection



```{r}
library(curl)

raw <- curl("https://raw.githubusercontent.com/allisondavis/morphology_analysis/master/adavis_morph-raw_all.csv")

raw <- read.csv(raw, header = TRUE, sep = ",", stringsAsFactors = TRUE)

head(raw)

form <- curl("https://raw.githubusercontent.com/allisondavis/morphology_analysis/master/adavis_morph-raw_formosa.csv")

form <- read.csv(form, header = TRUE, sep = ",", stringsAsFactors = TRUE)

head(form)

lat <- curl("https://raw.githubusercontent.com/allisondavis/morphology_analysis/master/adavis_morph-raw_latipinna.csv")

lat <- read.csv(lat, header = TRUE, sep = ",", stringsAsFactors = TRUE)

head(lat)

```

#### BOX PLOTS

```{r echo=FALSE}

library(ggplot2)

ggplot(raw, aes(x=SPP, y=D)) + geom_boxplot() + xlab("Species") + ylab("Ray count") + ggtitle("Dorsal ray comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=P1)) + geom_boxplot() + xlab("Species") + ylab("Ray count") + ggtitle("Left pectoral ray comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=P2)) + geom_boxplot() + xlab("Species") + ylab("Ray count") + ggtitle("Pelvic ray comparison") + geom_jitter(shape=16, position=position_jitter(0.2)) #need to do an average or separate out pelvic right and pelvic left

ggplot(raw, aes(x=SPP, y=A)) + geom_boxplot() + xlab("Species") + ylab("Ray count") + ggtitle("Anal ray comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=P1.R)) + geom_boxplot() + xlab("Species") + ylab("Ray count") + ggtitle("Right pectorcal ray comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=LLSC)) + geom_boxplot() + xlab("Species") + ylab("Scale count") + ggtitle("Lateral line scale comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=SALL)) + geom_boxplot() + xlab("Species") + ylab("Scale count") + ggtitle("Scales above Lateral line comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=SBLL)) + geom_boxplot() + xlab("Species") + ylab("Scale count") + ggtitle("Scales below Lateral line comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=SBDF)) + geom_boxplot() + xlab("Species") + ylab("Scale count") + ggtitle("Scales before dorsal fin comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=TL)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Total length comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=SL)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Standard length comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=BD)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Body depth comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=CPD)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Caudal peduncle comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=CPL)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Caudal peduncle length comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=PreDL)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Pre-dorsal length comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=DbL)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Dorsal base length comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=HL)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Head length comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=HD)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Head depth comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=HW)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Head width comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=SnL)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Snout length comparison") + geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(raw, aes(x=SPP, y=OL)) + geom_boxplot() + xlab("Species") + ylab("Size (mm)") + ggtitle("Orbital length comparison") + geom_jitter(shape=16, position=position_jitter(0.2))



```



#### T.TESTS

```{r}
#doral ray counts
t.test(lat$D, form$D, alternative = "two.sided")

#left pectoral ray counts
t.test(lat$P1, form$P1, alternative = "two.sided")

#won't do pelvic, since it's currently in weird format

#anal ray counts
t.test(lat$A, form$A, alternative = "two.sided")

#right pectoral ray counts
t.test(lat$P1.R, form$P1.R, alternative = "two.sided")

#lateral line scale count
t.test(lat$LLSC, form$LLSC, alternative = "two.sided")

#scales above lateral line
t.test(lat$SALL, form$SALL, alternative = "two.sided")

#scales below lateral line
t.test(lat$SBLL, form$SBLL, alternative = "two.sided")

#scales before dorsal fin
t.test(lat$SBDF, form$SBDF, alternative = "two.sided")

#total length
t.test(lat$TL, form$TL, alternative = "two.sided")

#standard length
t.test(lat$SL, form$SL, alternative = "two.sided")

#body depth
t.test(lat$BD, form$BD, alternative = "two.sided")

#caudal peduncle depth
t.test(lat$CPD, form$CPD, alternative = "two.sided")

#caudal peduncle length
t.test(lat$CPL, form$CPL, alternative = "two.sided")

#pre dorsal length
t.test(lat$PreDL, form$PreDL, alternative = "two.sided")

#dorsal base length
t.test(lat$DbL, form$DbL, alternative = "two.sided")

#head length
t.test(lat$HL, form$HL, alternative = "two.sided")

#head depth
t.test(lat$HD, form$HD, alternative = "two.sided")

#head width
t.test(lat$HW, form$HW, alternative = "two.sided")

#snout length
t.test(lat$SnL, form$SnL, alternative = "two.sided")

#oribital length
t.test(lat$OL, form$OL, alternative = "two.sided")

```

#### VARIANCE TESTS

```{r}
#doral ray counts
var.test(lat$D, form$D, alternative = "two.sided")

#left pectoral ray counts
var.test(lat$P1, form$P1, alternative = "two.sided")

#won't do pelvic, since it's currently in weird format

#anal ray counts
var.test(lat$A, form$A, alternative = "two.sided")

#right pectoral ray counts
var.test(lat$P1.R, form$P1.R, alternative = "two.sided")

#lateral line scale count
var.test(lat$LLSC, form$LLSC, alternative = "two.sided")

#scales above lateral line
var.test(lat$SALL, form$SALL, alternative = "two.sided")

#scales below lateral line
var.test(lat$SBLL, form$SBLL, alternative = "two.sided")

#scales before dorsal fin
var.test(lat$SBDF, form$SBDF, alternative = "two.sided")

#total length
var.test(lat$TL, form$TL, alternative = "two.sided")

#standard length
var.test(lat$SL, form$SL, alternative = "two.sided")

#body depth
var.test(lat$BD, form$BD, alternative = "two.sided")

#caudal peduncle depth
var.test(lat$CPD, form$CPD, alternative = "two.sided")

#caudal peduncle length
var.test(lat$CPL, form$CPL, alternative = "two.sided")

#pre dorsal length
var.test(lat$PreDL, form$PreDL, alternative = "two.sided")

#dorsal base length
var.test(lat$DbL, form$DbL, alternative = "two.sided")

#head length
var.test(lat$HL, form$HL, alternative = "two.sided")

#head depth
var.test(lat$HD, form$HD, alternative = "two.sided")

#head width
var.test(lat$HW, form$HW, alternative = "two.sided")

#snout length
var.test(lat$SnL, form$SnL, alternative = "two.sided")

#oribital length
var.test(lat$OL, form$OL, alternative = "two.sided")

```






